import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./features/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#005bbf",
        "primary-container": "#1a73e8",
        "on-primary": "#ffffff",
        "on-primary-container": "#ffffff",
        "on-primary-fixed": "#001a41",
        "on-primary-fixed-variant": "#004493",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#adc7ff",
        "inverse-primary": "#adc7ff",
        secondary: "#585d77",
        "secondary-container": "#dadefd",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#5c617c",
        "on-secondary-fixed": "#151a31",
        "on-secondary-fixed-variant": "#41455f",
        "secondary-fixed": "#dde1ff",
        "secondary-fixed-dim": "#c1c5e3",
        tertiary: "#4f5f75",
        "tertiary-container": "#68788f",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#000510",
        "tertiary-fixed": "#d3e4fe",
        "tertiary-fixed-dim": "#b7c8e1",
        "on-tertiary-fixed": "#0b1c30",
        "on-tertiary-fixed-variant": "#38485d",
        background: "#f8f9fa",
        "on-background": "#191c1d",
        surface: "#f8f9fa",
        "surface-dim": "#d9dadb",
        "surface-bright": "#f8f9fa",
        "surface-variant": "#e1e3e4",
        "surface-tint": "#005bc0",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "on-surface": "#191c1d",
        "on-surface-variant": "#414754",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f2",
        outline: "#727785",
        "outline-variant": "#c1c6d6",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        warning: "#f59e0b",
        "warning-container": "#fef3c7",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "16px",
        stack_sm: "8px",
        stack_md: "16px",
        stack_lg: "24px",
        sidebar_width: "260px",
        container_margin: "24px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "data-tabular": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-bold": ["var(--font-inter)", "Inter", "sans-serif"],
        "display-lg-mobile": ["var(--font-inter)", "Inter", "sans-serif"],
        "display-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-base": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "data-tabular": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "label-bold": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-base": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
