import {
  KPIStats,
  ScanRecord,
  QualityCheckItem,
  PipelineStage,
  AnalysisLog,
  ExtractedEntity,
  BoundingBox,
  DetectedDeclaration,
} from '@/types/compliance';

export const INITIAL_KPI_STATS: KPIStats = {
  totalScans: 1248,
  totalScansGrowth: '↑ 12.4%',
  passCount: 842,
  passPercentage: 67.5,
  reviewCount: 286,
  reviewPercentage: 22.9,
  failCount: 120,
  failPercentage: 9.6,
};

export const RECENT_SCANS: ScanRecord[] = [
  {
    id: 'SCN-10248',
    productName: 'Premium Rice 5 kg',
    category: 'Food & Beverage',
    date: '25 Aug 2026',
    status: 'PASS',
    confidence: 96,
    issueCount: 0,
    manufacturer: 'ABC Foods Pvt. Ltd.',
    mrp: '₹480',
    netQuantity: '5 kg',
  },
  {
    id: 'SCN-10247',
    productName: 'Cooking Oil 1 L',
    category: 'Food & Beverage',
    date: '25 Aug 2026',
    status: 'REVIEW',
    confidence: 72,
    issueCount: 2,
    manufacturer: 'Golden Harvest Oils',
    mrp: '₹175',
    netQuantity: '1 L',
  },
  {
    id: 'SCN-10246',
    productName: 'Biscuits 200 g',
    category: 'Food & Beverage',
    date: '24 Aug 2026',
    status: 'FAIL',
    confidence: 91,
    issueCount: 3,
    manufacturer: 'Bakery World Ltd.',
    mrp: '₹35',
    netQuantity: '200 g',
  },
  {
    id: 'SCN-10245',
    productName: 'Herbal Shampoo 250 ml',
    category: 'Cosmetics',
    date: '24 Aug 2026',
    status: 'PASS',
    confidence: 98,
    issueCount: 0,
    manufacturer: 'Ayur Naturals India',
    mrp: '₹220',
    netQuantity: '250 ml',
  },
  {
    id: 'SCN-10244',
    productName: 'Instant Noodles 70 g',
    category: 'Food & Beverage',
    date: '23 Aug 2026',
    status: 'PASS',
    confidence: 95,
    issueCount: 0,
    manufacturer: 'TasteBite Foods Ltd.',
    mrp: '₹14',
    netQuantity: '70 g',
  },
  {
    id: 'SCN-10243',
    productName: 'Pure Cow Ghee 500 ml',
    category: 'Dairy',
    date: '23 Aug 2026',
    status: 'REVIEW',
    confidence: 84,
    issueCount: 1,
    manufacturer: 'Vedic Dairy Farms',
    mrp: '₹390',
    netQuantity: '500 ml',
  },
];

export const QUALITY_CHECK_ITEMS: QualityCheckItem[] = [
  {
    id: 'res',
    title: 'Resolution',
    statusText: 'Pending check...',
    status: 'pending',
    icon: 'lens_blur',
  },
  {
    id: 'framing',
    title: 'Framing Complete',
    statusText: 'Simulated Pass',
    status: 'good',
    icon: 'aspect_ratio',
  },
  {
    id: 'lighting',
    title: 'Lighting acceptable',
    statusText: 'Slight glare detected',
    status: 'warning',
    icon: 'wb_incandescent',
  },
  {
    id: 'orientation',
    title: 'Orientation',
    statusText: 'Image skewed > 15 deg',
    status: 'error',
    icon: 'crop_rotate',
  },
];

export const PIPELINE_STAGES: PipelineStage[] = [
  {
    id: 'read',
    name: 'Read',
    progress: 78,
    status: 'active',
    icon: 'document_scanner',
    description: 'Image preprocessing, OCR text extraction, Bounding-box detection.',
  },
  {
    id: 'understand',
    name: 'Understand',
    progress: 0,
    status: 'pending',
    icon: 'psychology',
    description: 'Declaration extraction, Entity identification.',
  },
  {
    id: 'check',
    name: 'Check',
    progress: 0,
    status: 'pending',
    icon: 'rule',
    description: 'Rule matching, Compliance evaluation.',
  },
  {
    id: 'explain',
    name: 'Explain',
    progress: 0,
    status: 'pending',
    icon: 'assignment',
    description: 'Evidence generation, Compliance report.',
  },
];

export const INITIAL_ANALYSIS_LOGS: AnalysisLog[] = [
  { id: '1', message: 'Image preprocessing complete', status: 'complete' },
  { id: '2', message: 'Text regions detected', status: 'complete' },
  { id: '3', message: 'Extracting declarations...', status: 'running' },
  { id: '4', message: 'Applying compliance rules', status: 'pending' },
  { id: '5', message: 'Preparing evidence', status: 'pending' },
];

export const OCR_BOUNDING_BOXES: BoundingBox[] = [
  {
    id: 'mrp',
    label: 'MRP - 98%',
    confidence: 98,
    top: '15%',
    left: '60%',
    width: '120px',
    height: '40px',
    color: 'border-primary bg-primary/20 hover:bg-primary/30',
    bgOpacity: 'bg-primary text-on-primary',
  },
  {
    id: 'net_qty',
    label: 'Net Qty - 96%',
    confidence: 96,
    top: '35%',
    left: '20%',
    width: '140px',
    height: '44px',
    color: 'border-teal-500 bg-teal-500/20 hover:bg-teal-500/30',
    bgOpacity: 'bg-teal-500 text-white',
  },
  {
    id: 'mfg',
    label: 'Manufacturer - 94%',
    confidence: 94,
    top: '60%',
    left: '10%',
    width: '210px',
    height: '65px',
    color: 'border-indigo-500 bg-indigo-500/20 hover:bg-indigo-500/30',
    bgOpacity: 'bg-indigo-500 text-white',
  },
];

export const EXTRACTED_ENTITIES: ExtractedEntity[] = [
  {
    id: '1',
    name: 'MRP',
    extractedValue: '₹120',
    confidence: 98,
    status: 'good',
    colorDot: 'bg-primary',
  },
  {
    id: '2',
    name: 'Net Quantity',
    extractedValue: '500 g',
    confidence: 96,
    status: 'good',
    colorDot: 'bg-teal-500',
  },
  {
    id: '3',
    name: 'Manufacturer',
    extractedValue: 'ABC Foods Pvt Ltd',
    confidence: 94,
    status: 'good',
    colorDot: 'bg-indigo-500',
  },
  {
    id: '4',
    name: 'Packing Date',
    extractedValue: 'JUL 2026',
    confidence: 82,
    status: 'warning',
    colorDot: 'bg-orange-400',
  },
  {
    id: '5',
    name: 'Consumer Care',
    extractedValue: '1800-XXX-XXXX',
    confidence: 91,
    status: 'good',
    colorDot: 'bg-blue-400',
  },
];

export const INITIAL_DECLARATIONS: DetectedDeclaration[] = [
  {
    id: 'decl-1',
    key: 'common_name',
    label: 'Common Name',
    value: 'Rice',
    confidence: 97,
    evidenceImageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAAU3ranM15SAG_xqt-7ZZy8BMMvqB08Ft6RhHvCydF4Q7DVp9998gS_UfwsULXZsR61oZ-60LerbtvBe64CKZT9BDf-8eZbZJYhqGmiR4U37JvsEJm_L29j6eV2-KTLC4Zq_nKbd9Y5-rHIOHgePjWM9-UgXShaexL6P9VL_HU6RdRc2GC4bN9A-rLLDUE6JOSnwyNzS0CUigzx9Z-jOwhKDHbDTxrmXN5J3S4zrqaAXQphiJN3qs_',
  },
  {
    id: 'decl-2',
    key: 'net_quantity',
    label: 'Net Quantity',
    value: '5 kg',
    confidence: 99,
    evidenceImageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAAU3ranM15SAG_xqt-7ZZy8BMMvqB08Ft6RhHvCydF4Q7DVp9998gS_UfwsULXZsR61oZ-60LerbtvBe64CKZT9BDf-8eZbZJYhqGmiR4U37JvsEJm_L29j6eV2-KTLC4Zq_nKbd9Y5-rHIOHgePjWM9-UgXShaexL6P9VL_HU6RdRc2GC4bN9A-rLLDUE6JOSnwyNzS0CUigzx9Z-jOwhKDHbDTxrmXN5J3S4zrqaAXQphiJN3qs_',
  },
  {
    id: 'decl-3',
    key: 'mrp',
    label: 'MRP',
    value: '₹480',
    confidence: 98,
    evidenceImageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAAU3ranM15SAG_xqt-7ZZy8BMMvqB08Ft6RhHvCydF4Q7DVp9998gS_UfwsULXZsR61oZ-60LerbtvBe64CKZT9BDf-8eZbZJYhqGmiR4U37JvsEJm_L29j6eV2-KTLC4Zq_nKbd9Y5-rHIOHgePjWM9-UgXShaexL6P9VL_HU6RdRc2GC4bN9A-rLLDUE6JOSnwyNzS0CUigzx9Z-jOwhKDHbDTxrmXN5J3S4zrqaAXQphiJN3qs_',
  },
  {
    id: 'decl-4',
    key: 'manufacturer',
    label: 'Manufacturer/Packer',
    value: 'ABC Foods Pvt. Ltd.',
    confidence: 94,
    evidenceImageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAAU3ranM15SAG_xqt-7ZZy8BMMvqB08Ft6RhHvCydF4Q7DVp9998gS_UfwsULXZsR61oZ-60LerbtvBe64CKZT9BDf-8eZbZJYhqGmiR4U37JvsEJm_L29j6eV2-KTLC4Zq_nKbd9Y5-rHIOHgePjWM9-UgXShaexL6P9VL_HU6RdRc2GC4bN9A-rLLDUE6JOSnwyNzS0CUigzx9Z-jOwhKDHbDTxrmXN5J3S4zrqaAXQphiJN3qs_',
  },
  {
    id: 'decl-5',
    key: 'packing_date',
    label: 'Packing Date',
    value: 'July 2026',
    confidence: 82,
    reviewRequired: true,
    warningNote: 'Confidence score (82%) is below verified threshold. Date format contains ambiguous typography.',
    evidenceImageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAAU3ranM15SAG_xqt-7ZZy8BMMvqB08Ft6RhHvCydF4Q7DVp9998gS_UfwsULXZsR61oZ-60LerbtvBe64CKZT9BDf-8eZbZJYhqGmiR4U37JvsEJm_L29j6eV2-KTLC4Zq_nKbd9Y5-rHIOHgePjWM9-UgXShaexL6P9VL_HU6RdRc2GC4bN9A-rLLDUE6JOSnwyNzS0CUigzx9Z-jOwhKDHbDTxrmXN5J3S4zrqaAXQphiJN3qs_',
  },
  {
    id: 'decl-6',
    key: 'consumer_care',
    label: 'Consumer Care',
    value: '1800-XXX-XXXX',
    confidence: 91,
    evidenceImageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAAU3ranM15SAG_xqt-7ZZy8BMMvqB08Ft6RhHvCydF4Q7DVp9998gS_UfwsULXZsR61oZ-60LerbtvBe64CKZT9BDf-8eZbZJYhqGmiR4U37JvsEJm_L29j6eV2-KTLC4Zq_nKbd9Y5-rHIOHgePjWM9-UgXShaexL6P9VL_HU6RdRc2GC4bN9A-rLLDUE6JOSnwyNzS0CUigzx9Z-jOwhKDHbDTxrmXN5J3S4zrqaAXQphiJN3qs_',
  },
  {
    id: 'decl-7',
    key: 'country_of_origin',
    label: 'Country of Origin',
    value: 'India',
    confidence: 96,
    evidenceImageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAAU3ranM15SAG_xqt-7ZZy8BMMvqB08Ft6RhHvCydF4Q7DVp9998gS_UfwsULXZsR61oZ-60LerbtvBe64CKZT9BDf-8eZbZJYhqGmiR4U37JvsEJm_L29j6eV2-KTLC4Zq_nKbd9Y5-rHIOHgePjWM9-UgXShaexL6P9VL_HU6RdRc2GC4bN9A-rLLDUE6JOSnwyNzS0CUigzx9Z-jOwhKDHbDTxrmXN5J3S4zrqaAXQphiJN3qs_',
  },
];

export const RULE_DATABASE_ITEMS = [
  {
    id: 'RULE-PC-01',
    name: 'Legal Metrology (Packaged Commodities) Rule 6(1)(a)',
    clause: 'Declaration of Name and Address of Manufacturer, Packer or Importer',
    mandatory: true,
    standardPenalty: 'Section 36(1) Compoundable Notice',
    description: 'Every package shall bear the name and complete address of the manufacturer, or where the manufacturer is not the packer, the name and address of the manufacturer and packer.',
  },
  {
    id: 'RULE-PC-02',
    name: 'Legal Metrology (Packaged Commodities) Rule 6(1)(b)',
    clause: 'Common or Generic Names of the Commodity',
    mandatory: true,
    standardPenalty: 'Section 36(1) Compoundable Notice',
    description: 'The common or generic names of the commodity contained in the package and in case of packages with more than one product, the name and quantity of each product.',
  },
  {
    id: 'RULE-PC-03',
    name: 'Legal Metrology (Packaged Commodities) Rule 6(1)(c)',
    clause: 'Net Quantity in Standard Units of Weight or Measure',
    mandatory: true,
    standardPenalty: 'Section 36(1) Direct Seizure / Fine',
    description: 'The net quantity, in terms of the standard unit of weight or measure, of the commodity contained in the package or where the commodity is packed or sold by number, the number of the commodity contained in the package.',
  },
  {
    id: 'RULE-PC-04',
    name: 'Legal Metrology (Packaged Commodities) Rule 6(1)(d)',
    clause: 'Month and Year of Manufacture / Pre-packing / Import',
    mandatory: true,
    standardPenalty: 'Section 36(1) Notice',
    description: 'The month and year in which the commodity is manufactured or pre-packed or imported shall be mentioned clearly.',
  },
  {
    id: 'RULE-PC-05',
    name: 'Legal Metrology (Packaged Commodities) Rule 6(1)(e)',
    clause: 'Retail Sale Price (Maximum Retail Price - MRP inclusive of all taxes)',
    mandatory: true,
    standardPenalty: 'Section 36(1) Penalty up to ₹25,000 for first offence',
    description: 'The retail sale price of the package shall be declared as Maximum Retail Price (MRP) inclusive of all taxes.',
  },
  {
    id: 'RULE-PC-06',
    name: 'Legal Metrology (Packaged Commodities) Rule 6(1)(da)',
    clause: 'Unit Sale Price (USP)',
    mandatory: true,
    standardPenalty: 'Section 36(1) Compliance Warning',
    description: 'Unit sale price in rupees rounded off to the nearest two decimal places per g/ml or per kg/l.',
  },
  {
    id: 'RULE-PC-07',
    name: 'Legal Metrology (Packaged Commodities) Rule 6(1)(h)',
    clause: 'Consumer Care Contact Details',
    mandatory: true,
    standardPenalty: 'Section 36(1) Notice',
    description: 'Name, address, telephone number, email address of the person who can be contacted by the consumer in case of complaints.',
  },
];
